---
title: "Course Project"
author: "Shelby F"
date: "4/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(rpart)
library(rpart.plot)
set.seed(1234)
```

## Data Read

Data for this project is from  http://groupware.les.inf.puc-rio.br/har 
```{r data}
## Read in Training Data 
training <- read.csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", na.strings = c("NA", "#DIV/0!", ""))
dim(training)

## Read in Test Data
test <- read.csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", na.strings = c("NA", "#DIV/0!", ""))

## Clean data - remove columns with no data 
training<-training[,colSums(is.na(training)) == 0] 
test <- test[,colSums(is.na(test)) == 0]
```

```{r training subsetting}
subSet <- createDataPartition(y=training$classe, p=0.75, list=FALSE)
trainingSet <- training[subSet, ] 
testSet <- training[-subSet, ]
```

## Predict Type of Exercise

###
```{r rpart}
modFitRP <- train(classe ~., method = "rpart", data= trainingSet)
print(modFitRP)
qplot(predict(modFitRP, testSet), classe, data=testSet)

```

```{r gbm}
modFitGBM <- train(classe ~., data= trainingSet, method ="gbm")
print(modFitGBM)
qplot(predict(modFitGBM, testSet), classe, data=testSet)

```

```{r prediction}
predictfinal <- predict(modFitGBM, test)
print(predictfinal)
```


